import Head from "next/head";
import Navbar from "@/components/navbar";
import ProjectCard from "@/components/projectcard";
import ArticleCard from "@/components/articlecard";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>About - Alfred J. Lin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favi.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="max-auto bg-slate-50 min-h-screen flex flex-col">
        <div className="flex-1">
          <Navbar></Navbar>
          <ArticleCard link={"/"}></ArticleCard>
        </div>
        <Footer></Footer>
      </main>
    </>
  );
}
